/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hei' at '1/22/18 3:07 PM' with Gradle 2.14.1
 *
 * @author Hei, @date 1/22/18 3:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
